### ISSUE TITLE
Confusing - Guide vs Homepage and docs

### ISSUE THREAD

**Issue by OndeVai** [sst/sst#112]
I know you guys are in a transitionary period where you are moving from the serverless framework to your STS framework. However, for someone brand new to the site, the differences between the guide, which still teaches the serverless framework, and the rest of the docs which teach STS, make for a very confusing experience. 

IMO the guide is still the de facto place for comprehensively learning the serverless framework for now. Could you please spell out the differences and compare the 2 frameworks throughout the site to clarify?

Also, STS (which looks really cool) is very new, and will take a while to gain traction, especially as the framework solidifies and kinks are worked out --this could take months or years. In the meantime, I think it's vital to still provide your wonderful guide for the serverless framework prominently.

**Comment by jayair** [comment]
Appreciate the feedback @OndeVai. Yeah we are in a period of transition. But you are right, it's confusing right now. Also because we are using SST to do the infrastructure parts, while using Serverless Framework for Lambdas.

I should've elaborated on this in the newsletter but over the next couple of weeks we'll create separate guides for Serverless Framework and SST. We also want to have a guide for SAM at some point too. These guides will be available separately as eBooks as well.

I think this is a better approach, just show how to do things using the separate approaches and let readers pick the ones they want to learn. We'll also have other articles outlining the differences between the frameworks to help people decide.

**Comment by jayair** [comment]
Another thought here. It might be better to host the guides on a separate URL from the rest.

**Comment by OndeVai** [comment]
Thanks @jayair,

Yeah, I think that would make sense --and maybe link out to the other guides from the same SST homepage.

**Comment by jayair** [comment]
Yup. I like the way Stripe lists their guides, https://stripe.com/guides. We might do something similar.

**Comment by OndeVai** [comment]
Ideally, it would be nice to have a guide for the following:
1) Serverless API with just pure CDK
2) Serverless API with just pure serverless yaml
3) Serverless API mixing pure CDK and yaml
4) Serverless API with yaml and SST

I was able to sort of piece together my own from your guide and move forward with #3 above. The guide used to be product agnostic.

**Comment by fxyong** [comment]
is there any update on the guide with using SST?

**Comment by jayair** [comment]
We haven't yet but we have a working version of the backend part of the guide in SST here https://github.com/serverless-stack/serverless-stack/tree/master/packages/cli/test/start-guide

We are currently working on a SPA construct (https://github.com/serverless-stack/serverless-stack/discussions/194). That'll allow us to create a full-stack version of the guide in SST.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
