### ISSUE TITLE
Node 16 support with PROVIDED runtime

### ISSUE THREAD

**Issue by fwang** [sst/sst#1426]

**Comment by ErikMikkelson** [comment]
This would be useful in order to let people use [everynode](https://github.com/fusebit/everynode) instead of the AWS runtime.  We're now 2 LTS versions behind in the available AWS lambda runtimes for NodeJS.  Main drawbacks according to Fusebit are a longer deployment time for the function but not cold start time [issue](https://github.com/fusebit/everynode/issues/5)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
