### ISSUE TITLE
Fix VS Code high CPU usage and breakpoint not working

### ISSUE THREAD

**Issue by fwang** [sst/sst#1599]
Martin has tried:
- i set the srcPath for the project, however, this did not resolve the high CPU problem with VSCode that leads to the dropped requests & inability to debug.
- i’ve been running yarn sst start from the command line, not within VSCode. this totally resolves the high CPU issue. everything works perfectly outside of VSCode.

---
Request:
- Martin https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1644961390416499

**Comment by abirtley** [comment]
@fwang - If it helps, I have prepared a minimal reproduction repository here, which shows the breakpoint not working issue: https://github.com/abirtley/sst-breakpoint-repro  It is based on the typescript monorepo example, but using esbuild-jest instead of esbuild-runner so that I could use Jest and WallabyJS (see related issue here: https://github.com/wallabyjs/public/issues/2946)

This repository does not consistently reproduce the high CPU issue, but I confirm that I do also get very high CPU usage sometimes (not always). I am running MacOS BigSur, VS Code 1.66.2.

Processor: 4.2 GHz Quad-Core Intel Core i7  
Memory: 24 GB 2400 MHz DDR4

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
