### ISSUE TITLE
How to Deploy Specific stack using sst deploy

### ISSUE THREAD

**Issue by taufiqpirjade** [sst/sst#1674]
I have created the multiple stacks for my frontend and backend. Currently `sst deploy ` command does everything.
What if I want to deploy specific stack like just backend one. I have not found anything on in official documentation.

Is there any option of deploying specific stack

**Comment by fwang** [comment]
Hey @taufiqpirjade, we’ve got a couple of things on the roadmap that could fix this:
- possible fix 1: only building Functions in the stack to be deployed https://github.com/serverless-stack/serverless-stack/issues/1755
- possible fix 2: run sst build once, and sst deploy reuse the built artifact, instead of building again https://github.com/serverless-stack/serverless-stack/issues/779

I bumped up the priority for both issues.

For now, here’s a work around. Define ur stack like this:
```js
const STACK = process.env.STACK;

(!STACK || STACK === "StackA") && app.stack(StackA);
(!STACK || STACK === "StackB") && app.stack(StackB);
(!STACK || STACK === "StackC") && app.stack(StackC);
```

And this will only build and deploy a single stack
```bash
STACK=StackA sst deploy
```

And this will deploy all stacks
```bash
sst deploy
```

**Comment by fwang** [comment]
Keeping track a list of requests for this feature:
- Justin90 https://discord.com/channels/983865673656705025/1011593828169433138/1011741684448628867

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
