### ISSUE TITLE
SyntaxError: The requested module 'ws' does not provide an export named 'WebSocketServer'

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1735]
Working on my sst+prisma template repo

Error: https://github.com/jetbridge/sst-prisma/runs/6586510573?check_suite_focus=true
Code: https://github.com/jetbridge/sst-prisma/tree/lint-prettier
Test: https://github.com/jetbridge/sst-prisma/blob/lint-prettier/stacks/main.test.ts

**Comment by fwang** [comment]
This should be fixed in a recent release. @thdxr can confirm.

**Comment by revmischa** [comment]
I solved the problem in sst-prisma by switching to vitest but in trying to upgrade my bigger project to sst 1.x I failed with this error, and can't easily migrate that to vitest (I'm trying but it's pretty hard)

**Comment by AshHeskes** [comment]
This still isn't fixed when trying to run jest with experimental esmodules enabled. It might be worth noting that I'm using jest with `esbuild-jest` to transform my tests. 

As per the esbuild docs (which I'm fairly certain is the same heuristic used by others e.g. babel) "Entry points with exports in CommonJS module syntax will be converted to a single default export of the value of module.exports".

Thus there is in fact no export named 'WebSocketServer'. To make the issue more complicated using an cjs output format for my code brings an error because you hardcode `const __dirname =` which in a CJS environment is already declared. (I will open another issue for this).

Long and short is that there's no way to run tests with jest.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
