### ISSUE TITLE
Accessing stack return constructs from the App construct.

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#1951]
When composing multiple stacks in a single App how do I access the return of each stack instantiated with `app.stack(stackFN)`? 

In this context I don't mean if the stack uses `stack.addOutputs()` as in literally the stack returns `return { someLambdaHandler, someQueue }`.

It seems the function call `app.stack()` returns the `app`. How is composition like this intended to work?

**Comment by AshHeskes** [comment]
I will add some further context to this so it's clearer.

I have a folder structure like so.

```
- modules
    - email
        - Stack.js // returns a Queue
    - api
        - Stack.js // returns a Function
App.js // imports both email/Stack.js and api/Stack.js.
```

I'm wanting to add permissions for the queue returned by `email/Stack.js` to the lambda fn returned by `api/Stack.js` in `App.js`. Whilst also passing in the `queueUrl` returned by `email/Stack.js` to `api/Stack.js` as a prop. The stack fns for both functions are wrapped in a fn to accept vars and return the actual stack function.

```js
// email/Stack.js
function setupEmailStack ( config ) {

    return function emailStack( { stack, app } ) {
        return {
            email_queue: new Queue( stack, "EmailQueue" );
        }
    }

}
```

Which then are instantiated in `App.js` like so.

```js
import setupEmailStack from "email/Stack";

export default function main (app) {
    // as an example of passing env vars from the root rather than the stack needing explicit knowledge of them.
    const emailStack = setupEmailStack ( { ...process.env } );
    
    const { email_queue } = app.stack(emailStack);
    
    // email queue is undefined, the return of the call `app.stack()` is basically `this`. 
} 
```

I know there's a `use()` function but that doesn't seem to be what I want. Since I don't necessarily need one stack to depend on the existence of another and as I understand it `use()` only works in the context of another stack not an `app`. Since `email/Stack.js` will have many other stacks using it. I just need the queue ARN and queue URL to pass to other stacks to attach permissions and know where to send messages.

This might be an anti-pattern and I'm completely missing the point, but it seems this kind of setup is possible in cloudFormation itself.

**Comment by AshHeskes** [comment]
So it turns out after reading the sst src that `use` can be used inside of app to do this kind of composition. Although I will say it would be much more convenient if `app.stack(myStack)` simply returned the stack `returns` like `use(myStack)` does. So we can avoid writing.

```js
// app.js
import myStack from "./my-stack";

export default function  (app) {
  app.stack(myStack);
  const my_stack_returns = use(myStack);
  
  // Which could be more simply expressed as
  const my_stack = use(app.stack(myStack));
  
  // but it seems far cleaner if we could just do.
  const my_stack = app.stack(myStack);
}
```

A brief look into the code it seems it could require just a slight refactor of the `app.stack` function to `return use(stack(this, fn, props))` instead of just `return stack(this, fn, props);`

**Comment by brinsleylogic** [comment]
Given your use case I'd say what you want is to just drop the `use(email_stack)` in to the api stack. I'm not clear on what you're trying to accomplish by trying to tie these stacks together in the initialisation function but the reason why the stack context is require for the `use` function is because you're creating a dependency on another stack. If the lambda needs to be tied to the queue, then it seems logical to import the queue to where the lambda is managed.

> This might be an anti-pattern and I'm completely missing the point, but it seems this kind of setup is possible in cloudFormation itself.

CloudFormation would just be doing the same dependency resolution as mentioned above.

> Although I will say it would be much more convenient if app.stack(myStack) simply returned the stack returns like use(myStack) does.

I think it was specifically designed to work with the idea in mind that you clearly mark your dependencies. If you have multiple stacks, compositing them in the app scope by chaining the `stack()` calls clearly shows in which order the stacks need to be generated, and unless you need to add/remove stacks, how your stacks use/declare resources should have to impact anything in that primary file. It's a separations of concern thing...

This is just all stuff I've gathered and half-recalled from chats with people on Discord (before that, Slack) and watching some of the streams with @thdxr.

Just throwing some info out there for you @AshHeskes :)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
