### ISSUE TITLE
Bundled files are not copied to build directory while using sst start

### ISSUE THREAD

**Issue by adikari** [sst/sst#2050]
I have a file that I would like to include in the bundle. I have included the `bundle.copyfiles` file in my lambda function definition.

The file gets copied correctly into the AWS lambda function. 

However, when I use `sst start` the file does not get copied to the local `.sst` build folder and I get an error.

**Comment by fwang** [comment]
Hey @adikari, yeah currently `sst start` doesn't respect the `bundle.copyFiles` option. The thinking was that when running the code locally, u have access to the file. We now realize this inconsistent behaviour of `sst start` vs `sst deploy` is confusing.

We are re-working our CLI to also copy files on `sst start`. This will be available in a few weeks. (part of a bigger change to sst start).

That said, for now, can u import the file instead of copying it? ie. say if you need to copy a `.csv` file, u can do this
```ts
import fileContent from "./path/to/csv/file"
```
This way, the file content is bundled right into ur code.

Let me know if this works for you.

**Comment by adikari** [comment]
Thanks @fwang . i will give that a go and see if that works for me. Looking forward for the sst cli update.

**Comment by adikari** [comment]
@fwang any updates on this? The approach you suggested won't work for me. The file I am dealing with is a `.graphql` file and without the appropriate loader, it won't work.

**Comment by liam-jones-lucout** [comment]
> We now realize this inconsistent behaviour of `sst start` vs `sst deploy` is confusing.

It's not just confusing, it's essentially broken. One of the primary reasons for using copyFiles is for none build time dependencies, (a graphql file being copied from one service into a stitching service is a good example). Without this working in SST start, it's a bit of an issue.

**Comment by ackinc** [comment]
+1. I'm trying to add SST to an existing nodejs project, and 'sst start' not respecting copyFiles is causing issues.

More details: The existing repo is a fastify api server + background jobs poller and workers. I'm slowly replacing specific workers with Lambda functions. I decided to add SST to the existing repo rather than make a new one to minimize code duplication.
