### ISSUE TITLE
Pothos does not generate schema when running sst build or sst deploy, only sst start

### ISSUE THREAD

**Issue by coamend** [sst/sst#2061]
This is reproducible easily by:

1. Run create-sst
2. Run npm install
3. Modify the article.ts type to change the output of the pothos builder (by commenting out the title field, for example) and save it
4. Run npx sst build or npx sst deploy

In either case, the schema.graphql file will not be updated to reflect the changes in step 3.

I believe this is also likely related to https://github.com/serverless-stack/sst/issues/1673, as I experienced something similar where I had an error in my schema (queries with a duplicate name), but those errors were not bubbled up during an sst build or sst deploy.

**Comment by thdxr** [comment]
Hey so there's currently a limitation with build + deploy due to CDK's design.  We cannot easily run async code and the pothos generator requires it currently.  This is why for the time being we're not gitignoring the code-generated files and they get checked in.

I have some ideas for how we can eventually get this working but there's some other work blocking it currently.

**Comment by jonnedeprez** [comment]
My current workaround for when I quickly want to generate the schema is a vitest that I mark as skipped for when I don't need it: 

```
describe.skip('schema', () => {
  it('should output the schema', () => {
    const schemaAsString = printSchema(lexicographicSortSchema(schema));

    writeFileSync('schema.graphql', schemaAsString);
  });
});
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
