### ISSUE TITLE
RemixSite: allow configuration for cache headers and cloudfront invalidation

### ISSUE THREAD

**Issue by seanWLawrence** [sst/sst#2267]
I'd like to contribute a feature for making the cache headers and cloudfront invalidation options configurable. For example, something like:

## API 

```ts
@default ['/*']
cloudfrontInvalidationPaths: string[],
@default CacheHeaders.DEFAULT
cacheHeaders: {[path: string], header: string}
```
> Note: if the cache headers from Remix will override these, then we may be able to just document that, i.e. `export function headers() {}` will override the default cache control headers [link]

## Steps

 - [ ] Research: how does the team feel about making these options configurable
 - [ ] Research: what's the best API for configuring the cache headers and invalidation options
 - [ ] Implement: make these configurable within the construct
 - [ ] Test: ensure the props output the correct CloudFormation
 - [ ] Doc: add examples and API information for configuring the cache headers and cloudfront invalidation

**Comment by bitpavel** [comment]
Hello, this feature would be extremely useful for us. Our platform has millions of pages that are updated rarely and quite heavy to be generated on the fly. 
We would like to add the cache on FE+CloudFront side (+ enable CloudFront Origin Shield) and use ISR for refreshing the data in background. But since CloudFront cache is invalidated after every new deployment, it isn't acceptable for us.
For now, we use a self-developed workaround to manage this cache (to store and refresh it). But we'll be happy to migrate to this new functionality, when SST provides the possibility to mange invalidation paths.

**Comment by jayair** [comment]
We'll accept PRs for this but let me understand what you are looking for.

You don't want some paths to be invalidated after every deployment?

How are you invalidating them (ISR) currently?

**Comment by bitpavel** [comment]
@jayair Right now we have an nginx-based proxy in front of our SST-based application. We're in the middle of migration from our old FE application to the new NextJS-based version and use this reverse proxy for routing. We've implemented the durable caching at this reverse proxy. 
We understand that it's a bad solution because it eliminates benefits of using CloudFront - CDN capabilities. So once we finish the migration (hope in couple months), we would like to remove this reverse proxy layer and route users directly to SST-based application. In this case, we will lose the caching capability as well.
Good to hear that you're open for PR, it's a working option for us.

**Comment by bitpavel** [comment]
Hey @jayair, I've create a PR: https://github.com/sst/sst/pull/3428
How can we proceed with it?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
