### ISSUE TITLE
Rust runtime

### ISSUE THREAD

**Issue by oscarthorn** [sst/sst#2335]
Hi!

Great framework! Any plans on supporting rust runtime for functions? It would be really great to be able to do local debugging of rust lambdas.

**Comment by thdxr** [comment]
yes I got a prototype working and I'm pretty eager to get it working for real - after sst2 launch!

**Comment by oscarthorn** [comment]
@thdxr Cool, that sounds great!

**Comment by aragalie** [comment]
@thdxr it would be great if you could please either add the functionality for it, or at least let us know roughly how to get it done ourselves in the meantime? It's currently the only thing blocking our team from switching to SST 🙏

**Comment by thdxr** [comment]
if you're curious to give it a try yourself you can take a look at the Go handler and a Rust one should be similar

https://github.com/serverless-stack/sst/blob/sst2/packages/sst/src/runtime/handlers/go.ts

**Comment by aragalie** [comment]
> if you're curious to give it a try yourself you can take a look at the Go handler and a Rust one should be similar
> 
> https://github.com/serverless-stack/sst/blob/sst2/packages/sst/src/runtime/handlers/go.ts

I'll give it a shot. If you have a minute, could you please just copy/paste here, from current experiments with the Rust part, what you changed in the `build:async...` part of the handler? Especially for the `execAsync()` function vs. the current **Go** implementation?
🙏
I'll work on from there 😁

**Comment by dbettin** [comment]
@thdxr What is the latest on supporting the Rust runtime? We are considering moving over to SST and need rust support.

Thanks!

**Comment by thdxr** [comment]
it's technically in there! can use the rust runtime, afk right now but check for the rust.ts file

we need a bit of help building it for a production lambda env, right now it's using a cargo plugin and I don't think that's necessary (had it working without before)

**Comment by aragalie** [comment]
@dbettin have a look here at @thdxr working through adding support to it in real time https://www.twitch.tv/videos/1734094943?t=02h27m10s. You'll understand better the current status, and also where things need to change (dropping cargo lambda plugin). 

Doing it without any plugin is quite feasible from what I understand, the main challenge is the build tooling for the functions when creating the bootstrap file. The snag here si that rust needs to do this in a way dependent on the architecture you're building it on (e.g if you're on a Mac, Win or Linux generally in CI/CD pipelines); 

SST would need to have a way to check your platform, and give you suggestions to what linker/build chain you need to install (if you don't have it already). Otherwise the cargo errors would be quite cryptic and unhelpful...

I'll give it a try as well soon to make a PR with a proposal for this, unless someone else figures out a better way before me...

Some useful resources: 
**Official docs**
- https://github.com/awslabs/aws-lambda-rust-runtime#1-cross-compiling-your-lambda-functions
- https://github.com/awslabs/aws-lambda-rust-runtime#22-deploying-with-the-aws-cli

**Examples in practice**
- https://youtu.be/Idys2BAmqIU?t=1552
- https://github.com/rust-adventure/building-a-dynamodb-powered-pokemon-api-with-cdk (see `Building the lambda binary`)

**Comment by beeinger** [comment]
Heyy @thdxr any updates on official support for rust?

**Comment by jayair** [comment]
Hmm might be better to ping him on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
