### ISSUE TITLE
NextJS Site URL `undefined`

### ISSUE THREAD

**Issue by iamalvisng** [sst/sst#2513]
I followed these 3 guides:
1. https://docs.sst.dev/quick-start
2. https://docs.sst.dev/constructs/Stack
3. https://docs.sst.dev/constructs/NextjsSite

I ended up with `site.url` being undefined. Not sure what did I miss.

```TS
// stacks/NextStack.ts

import { NextjsSite, StackContext } from "sst/constructs";

export function NextStack({ stack }: StackContext) {
  const site = new NextjsSite(stack, "Site", {
    path: "my-next-app",
  });

  console.log(site.url); // undefined
}
```

```TS
// stacks/APIStack.ts

import { StackContext, Api } from "sst/constructs";

export function API({ stack }: StackContext) {
  const api = new Api(stack, "api", {
    routes: {
      "GET /": "packages/functions/src/lambda.handler",
    },
  });
  stack.addOutputs({
    ApiEndpoint: api.url,
  });
}
```

```TS
// stacks/index.ts
import { API } from "./APIStack";
import { NextStack } from "./NextStack";

export default function main(app: any) {
  app.stack(API).stack(NextStack);
}
```

**Comment by CervarlCG** [comment]
I'm having a similar issue but when i try to remove a stage via `npx sst remove --stage XXX`

`Error: The stack output "URL" is undefined`

**Comment by rjerue** [comment]
Happens for me from the nextjs template for an easy example.

**Comment by fwang** [comment]
Hey everyone, sorry about the confusion.

`site.url` is `undefined` during development (ie. `sst dev`). When running `sst dev` the site is not really deployed. You are should run `next dev` to run the Next.js site locally.

A couple of things to note:
- since `site.url` is `undefined`, I often do this:
  ```ts
    stack.addOutputs({
      URL: site.url || "localhost",
    });
  ```
- in Next.js app's `package.json`, I change
  ```ts
  -   "dev": "next dev",
  +   "dev": "sst env next dev",
  ```
  `sst env` will pull in the values you set in `NextjsSite.environment` and make them available when running `next dev` locally.

I will update the docs and examples accordingly to reflect this.

Let me know if that makes sense.

**Comment by jgf5013** [comment]
@fwang not sure I understand. How does using environment variables help here? If the app is running on localhost, what port is being used?
