### ISSUE TITLE
Astro static generation doesn't fail build

### ISSUE THREAD

**Issue by bayssmekanique** [sst/sst#3442]
The default output mode for Astro sites is `static` (SSG), which isn't supported by the `astro-sst` adapter. The current implementation allows a successful build but fails at the deployment stage when the SSR function is not found (because it doesn't exist).

Either, the `astro-sst` adapter should detect the `outputMode: static` and immediately fail with a warning, or the `AstroSite` construct should be able to pivot when static content is detected to utilize the `StaticSite` construct.

**Comment by bblanke** [comment]
Since this is the case, docs should be updated to reflect that sst does not support static site generation.

The current page: [https://docs.sst.dev/constructs/AstroSite](https://docs.sst.dev/constructs/AstroSite) lists static site support as the first bullet point:

* It supports `static`, `server`, and `hybrid` modes.

**Comment by bayssmekanique** [comment]
@bblanke, this Issue was from a much older version of SST which didn't support static site generation. We've since done work to make it work, so the adapter docs are correct.
