### ISSUE TITLE
Is top-level await really necessary?

### ISSUE THREAD

**Issue by vinnichase** [sst/sst#3521]
Hey all,

this line from `sst/node/util/index.js:15`

```JS
const _placeholder = await parseEnvironment();
```

Is causing problems from time to time. Ofcourse I can workaround with `optimizeDeps` but this feels not great.

Top-level await is not supported in multiple modern build tools and it can lead to nasty problems when building sst in different environments. For me that was the case while building a custom plugin for astro.

I found out that removing the await in my node_modules folder solved the issue. The Environment was still loaded correctly.

This makes total sense because `let allVariables` is still populated during the execution of the promises. Its even better because it does not block the server startup. Even when I use config params on top-level in TS files, the config is populated.

The last point would be the only gotcha, since variables could not be imported while SST is in the process of parsing the environment. But that could maybe be mitigated by emitting an SST-Ready-event after parseEnvironment has finished.

**Comment by khuezy** [comment]
This is a tricky problem. In the case of loading configs/envs, you'd *want* to block server startup until the values are fully resolved.
There may be apps that depend on that assumption, so if you remove the await, the apps may break.

**Comment by vinnichase** [comment]
yeah I also had that in mind and it would definitely a breaking change. However I strongly consider that an edge case since server side code is mostly not invoked on startup but after the startup is complete (e.g. Page renders, calls of API routes). This is true for Astro and afaik also for Next.

I mean apparently I'm the only one seeing this as a problem 😄. So one could argue which case is more of an edge case.

But I think its still worth it to discuss if there are better ways.

Maybe turn off top-level await by config with dynamic imports.

**Comment by jayair** [comment]
I think we do want to deal with this and some related issues. We have some ideas here, I'll share this with the team.

**Comment by vinnichase** [comment]
Cool. Are there related issues where the discussion takes place?

I have basically two ideas to share. Haven't thought through it completely but maybe it can spend some inspiration:

1. All config values could be promises. They would have to be assigned to `allVariables` within a sync function and they always need to be awaited like `await Config.SOME_VALUE`. That would of course imply that config values can only be used within async functions. But the cool thing would be that the promises for all values are invoked on server startup and once they are resolved they can be fetched instantly with `await Config.SOME_VALUE`.
2. Split concepts of secrets and parameters. Parameters could be fetched on build time and baked into the .sst folder similar like `.sst/types/index.ts`. Secrets could be async values as suggested in 1. Parameters might be inserted at top-level whereas secrets should always be used in an async context (?)

Those are very rough ideas and I'm not seeing all implications. Just in case it helps

**Comment by benjamine** [comment]
just bumped into this issue (coming from https://discord.com/channels/983865673656705025/1202981804148265071/1204077118364065823 )
in an AstroSite, the top-level awaits cause some really hard to debug errors
(I had to find out it was future/auth by painful trial and error, adding/removing modules, and finally googling discovered the `optimizeDeps` trick).

I think the benefit of avoiding an `await` somewhere in the userland initialization of auth adapters isn't worth how problematic this is, even if it works, notice in many cases, a component (like the web ui in my case) only really needs to `Session.verify` (validate the JWT), so making them forcefully load all auth adapters (hitting external servers) adds unnecessary latency and brittleness.

in my case, I was sporadically getting a timeout because of this:

![image](https://github.com/sst/sst/assets/384553/5410c2e8-8746-4c3e-bd9b-807b133cc79f)

(this are a PITA bc I guess AWS lambda doesn't provide any helpful traces to understand what's going on)

to avoid the problem, a sligthly hacky workaround I ended up with, was recreating an implementation of `Session.verify` in my own code, to avoid loading `sst/node/future/auth` in astro:

``` ts
import { createVerifier } from 'fast-jwt';
import { Config } from 'sst/node/config';

interface SessionTypes {
  user: {
    userId: string;
    email: string;
  };
  account: {
    accountId: string;
  };
}

export type SessionValue = {
  [type in keyof SessionTypes]: {
    type: type;
    properties: SessionTypes[type];
  };
}[keyof SessionTypes];

function getPublicKey() {
  return Config.authPublicKey;
}

export function sessionVerify<T = SessionValue>(token: string) {
  // this function is a local clone of the one in sst/node/future/auth
  // eslint-disable-next-line no-secrets/no-secrets
  // see the original code at https://github.com/sst/sst/blob/c1b55e97a475ec0cca5422ee401431d036c40033/packages/sst/src/node/future/auth/session.ts#L110
  // this avoids the problems importing node/sst/future/await including top-level awaits
  // see https://discord.com/channels/983865673656705025/1202981804148265071/1203819857045626922
  if (token) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      const jwt = createVerifier({
        algorithms: ['RS512'],
        key: getPublicKey(),
      })(token);
      return jwt as T;
    } catch (error) {
      // this just means the token is invalid, so continue as unauthenticated
    }
  }
  return {
    type: 'public',
    properties: {},
  };
}
```

Maybe a simple solution without breaking backwards-compat, could be exposing `Session` (or `Session.verify`) in a separate module that doesn't load the auth adapters, no top-level awaits.

your Auth function can load the full AuthHandler and adapters, and let your ui or other components verifying authentication load only this `Session.verify` from somewhere else like `sst/node/future/auth-verify`

**Comment by jayair** [comment]
Thankfully top level await is going away with Ion https://github.com/sst/ion

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
