### ISSUE TITLE
Stuck at removing SSL for domain linked to ApiGatewayV2

### ISSUE THREAD

**Issue by YoussefKababe** [sst/sst#3988]
Hi there!

When removing a deployment, SST fails to remove the SSL ceritifcate and the domain linked to the Api gateway, it just gets stuck indefinitely at this step:

`ProjectNameSsl sst:aws:Certificate → ProjectNameSslCertificate aws:acm:Certificate`

Done some quick testing and it appears the issue was introduced by this commit: https://github.com/sst/ion/commit/11d96c92d2e68c95543bf578d2855d824ca334ee

**Comment by cosmic-ascendant** [comment]
This might be relevant -- issue I posted on discord below. I was finding that I couldn't remove apigatewayv2 as it was hanging on removing the cert, which itself had attached application load balancers. You can inspect .sst/log/event.log to see if the resource is timing out instead of waiting hours.

FWIW I actually went from ApiGatewayV2 to V1. But then had issues with V1 issuing the cert in the wrong region. Ultimately I decided to switch to a simple `sst.aws.Router` which a) is less expensive and b) moved all the gw capabilities like rate limiting, cors, and caching to my application. This has actually made everything substantially better! 

------------------
Strange behavior when attempting to remove an aws.ApiGatewayV2.. The certificate (ACM) coupled to it has 3 associated elastic load balancing resources with an unrecognized account id. 

This anomalous behavior has happened before, and eventually they disappear and allow me to delete the cert. 

Am I missing something with how/why these are created and associated? There is not way to delete the associated resources since they are under a different account.

```typescript
export const api = new sst.aws.ApiGatewayV2("TestAPI", {
  cors: true,
  domain: {
    name: $app.stage === "production"
      ? `api.${baseDomain}`
      : `api.${$app.stage}.${baseDomain}`,
  },
  transform: {
    api: (args) => {
      args.body = updatedOpenApiSpec;
    },
    stage: (args) => {
      // Set stage name
      args.name = $app.stage;

      // Set throttling for all routes
      args.defaultRouteSettings = {
        throttlingBurstLimit: 100,
        throttlingRateLimit: 50,
      };
    }
  }
});
```
<@336363751345356801> Yep turns out the ALB is created and owned by the API GW, and thus has an AWS internal account id. Regarding certificate removal (the only resource that fails to get removed from the GW), I reached out to AWS support and this is actually a  known issue of theirs 😞  I wish there was a better way to mitigate this, but I don't think there is any SST logic that could improve. Here is their response.

"API Gateway customers may encounter an issue when trying to delete custom domain names. The domain is mapped to an ALB managed by API Gateway. This ALB has a certificate attached that is not consistently deleted when the domain is deleted. We are aware of this issue and are working on a fix. In the meantime, if you encounter this issue, you can reach out to AWS Support for these certificates to be deleted by us. Additionally, these workarounds can help to reduce the frequency of or entirely avoid encountering this issue:

1. If you are using create and delete domain name operations in the same IaaC stack, splitting the certificate deletion and the domain deletion operations into separate stacks or configurations will reduce the issue. This can be done through Terraform or any other existing configuration mechanism. This will allow changes to the rest of the customer environment while bypassing this issue.

2. If you are creating domains immediately after deleting domains, adding a time gap of approximately 1 hour between the creation and deletion of domain and certificates gives the deletion process enough time to finish cleanly and reduces the probability of encountering this issue.

3. If you are using multiple base path mapping operations across HTTP/REST and are using v2 client, attaching HTTP API first in the operations will reduce the probability of encountering this issue.

4. If you are using multiple base path mapping operations with only REST APIs, using v1 client will reduce the probability of encountering this issue."

**Comment by fwang** [comment]
@cosmic-ascendant Thanks for the update!!

@gustavgenberg @YoussefKababe so here's the dependency tree:
```
Domain Mapping
  --> Domain Name --> Certificate
  --> Api
```
So the `domain mapping` depends on both `domain name` and `api`. And `domain name` depends on `certificate`.

> sst tries to remove the certificate before the dependent ApiGateway.

Note `api` and `certificate` are not related to each other, so it doesn't make sense to remove `certificate` before `api`. Especially when you are just trying to remove the domain (not `sst remove` case).

It seems we have to wait for the AWS fix. Is there something we can do to alleviate this?

**Comment by YoussefKababe** [comment]
@fwang thanks for checking this out. It's clear that the problem is on AWS side so I think there's nothing to do except hoping for a fix from them soon.

Should we close this or leave it open until there's a fix?

**Comment by fwang** [comment]
Yeah let's close this for now.

**Comment by onelesd** [comment]
I know this is an upstream problem, but wondering if it’s worth applying this [workaround](https://github.com/pulumi/pulumi/issues/5186#issuecomment-677136141) in the ApiGatewayV2 component. It mirrors the AWS internal dependency with pulumi’s `dependsOn`.

**Comment by angelgarrido** [comment]
Solved here: https://github.com/sst/sst/issues/5465 thankyou @fwang
