### ISSUE TITLE
Allow to change lambda name in `api.route` transform

### ISSUE THREAD

**Issue by jorenvh1** [sst/sst#4473]
We noticed that SST is trying to make sure all resources have a unique name by giving them random names. In some cases it's possible to adjust the names using the `transform` but for `api.route` it's not possible the change the lambda function's name.

It would be nice to allow this option.

**Comment by jonathanbiard** [comment]
@jayair Another use-case is for those who want to give public access to a bucket but control the domain with a CNAME rather than have the long AWS domain name or go through CloudFront. AWS requires the bucket name to be the same as the CNAME for this configuration so there cannot be any randomness or any prefixes to the bucket resource name for the CNAME to work.

I can also see a good number of possibilities where you might want to control resources by their respective domain names as well which all imply they'll already have uniqueness in the name since domain names will have the stage as part of it.

Overall, I think it's a good idea to always let the user be the master of their own naming conventions, if they so wish. The default automatic naming convention is great for those who don't need these specifics but a way to control them is always going to have some use, especially considering that the future may hold more AWS changes that will require control over naming as well.
