### ISSUE TITLE
Add Java Support

### ISSUE THREAD

**Issue by thdxr** [sst/sst#652]
### what commands are you running to build ur Java lambdas?

Jimmy:
> we currently only have scala lambdas, and it differ from Java up until the JAR is produced, then it’s handled just like any Java JAR.
> Like Pål says we use SBT to both build our Scala projects (though no gradle in there atm) and handle the package management for them. Builds are done within docker containers with the proper scala and sbt versions
> we’re basically doing it like this https://github.com/fancellu/scala-sam-app
> so in our build scripts we first do sbt assembly which produces a JAR
> and then we do the same sam packageas one does for Java

### Requests:
- https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628151773039100
- Jimmy https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628151773039100

**Comment by harish-lifex** [comment]
Any idea when this will be prioritised ?

**Comment by dundalek** [comment]
I am happy to report that SST lambdas work also well with Clojure, which is another JVM-based language. The standard way is to package into a `jar` file, which runs on the Java runtime without issues.

There are several build tools that get used, the official `clojure` CLI tool is a primary one, but there is also [Leiningen](https://leiningen.org/) (older, but still sees some usage) or [Babashka](https://babashka.org/) (gaining popularity recently, includes great task runner). Therefore the invocations can vary.

Probably most flexible way would be ability to pass arbitrary command, perhaps something like a `buildCommand` parameter:

```js
  java: {
    buildCommand: "clojure -T:build my-lambda",
  }
```

One specific consideration for Clojure is that it has several seconds startup time penalty which might add up if there are many lambdas and a new clojure build process were to be started for each one. I can imagine it could be useful to have ability to avoid running any build commands by SST, do a build up front, and let SST just collect the artifacts, e.g. `clojure -T:build && sst deploy`.

---

To make it work with existing SST implementation I came up with two possible workarounds. It should also be applicable to SBT for Scala or other JVM-based languages.

a) Add a task to `build.gradle` that invokes the actual command. This still requires `gradle` to be installed, which just forwards it.

```groovy
task build() {
  exec {
   commandLine 'clojure', '-T:build', 'my-lambda'
  }
}
```

b) Exploit the fact that SST looks for Gradle wrapper. Create a `gradlew` file and make it executable `chmod +x gradlew`:

```sh
#!/usr/bin/env sh

clojure -T:build my-lambda
```

This feels a bit dirty :) but I like it even better since it does not require Gradle to be installed at all. The `build.gradle` file still needs to present since SST searches for it and won't continue without it, but it can be blank.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
