### ISSUE TITLE
Better Python support

### ISSUE THREAD

**Issue by fwang** [sst/sst#667]
### Purpose
We need to improve Python support in SST. Let's use this issue to track all the Python-related issues/questions people have.

- Where/how are the Python dependencies needed in my Lambdas managed (since I'm seeing node stuff everywhere else)?
- What happens when I run npx sst test? I know Jest is a part of serverless stack, so what happens with whatever Python testing framework I'll end up using (for domain object unit tests)? Does the test command detect that and respond accordingly, or do I have to wire that up? Or, do I just run a separate command to run the Python tests?

**Comment by dancoates** [comment]
To expand on the Python dependency point, I've found that working with dependencies for python lambda functions while developing locally is a bit clunky.

I'm using poetry to install dependencies and when running `sst build` the docker build is quite smart about recognising the `pyproject.toml` or `poetry.lock` and outputting a `requirements.txt` via poetry before installing with pip. This seems to work quite well.

However when devving locally using `sst start` it seems that sst takes a bit more of a naïve approach and just runs the handler using the system version of python. This means that the dependencies installed with poetry are not available to the handler, and would need to be installed globally to work.

It is possible to make this work at the moment by setting the `VIRTUAL_ENV` environment variable when running `sst start` but this only works if you have just one python function and is quite un-ergonomic. 

It would be nice if the code in `runner.ts` could detect that the handler is set up using poetry or another dependency manager and change how it is run, by either

- adding the correct virtual env to the PATH using  `poetry env info -p` or similar
- running the handler using `poetry run` rather than via the system python version

**Comment by subssn21** [comment]
I'd like to see support for automatic layer generation like chalice has. Chalice can take all the dependencies and bundle them together in a layer so that it doesn't have to repackage them in a zip for each function.

**Comment by christiankaindl** [comment]
> It is possible to make this work at the moment by setting the VIRTUAL_ENV environment variable when running sst start but this only works if you have just one python function and is quite un-ergonomic.

Hi @dancoates thanks for this hint, we're currently also struggling with this. What did you put as "VIRTUAL_ENV"? We've tried the name of the virtual env profile as well as the full filesystem path, but no luck. We're on Ubuntu.

On macOS we could work around that by installing the packages globally, but on Ubuntu we this isn't so easy as well.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
