### ISSUE TITLE
AppSyncApi: validate schema on build

### ISSUE THREAD

**Issue by fwang** [sst/sst#675]
The validation code shared by David
```
const parseSchema = require("graphql/language").parse;
try {
  parseSchema(graphQLSchemaAsString);
} catch (e) {
  // parse failed
}
```

---
_Requested by [David Martin](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628629883152200)_

**Comment by iamdavidmartin** [comment]
Ok, these two should work for the unit tests. Taken from my schema, but vastly simplified, obviously. The error in the invalid schema is that PostInput is missing.

[graphQL-schemas.zip](https://github.com/serverless-stack/serverless-stack/files/6964814/graphQL-schemas.zip)

**Comment by iamdavidmartin** [comment]
Ok, these two should work for the unit tests. Taken from my schema, but vastly simplified, obviously. The error in the invalid schema is that PostInput is missing.

[Archive.zip](https://github.com/serverless-stack/serverless-stack/files/6964839/Archive.zip)

Also, I copy/pasted that code from my previous CLI. It used a require (vs import) bc I just ran node from the CLI with to typescript. I'm sure it will work with an import.

**Comment by fwang** [comment]
@iamdavidmartin It seem the invalid schema was able to be parsed. The invalid schema I used is this:
```
schema {
  query: Query
  mutation: Mutation
}

type Query {
  getPost(primaryId: String): Post
}

type Mutation {
  addPost(post: PostInput!): Post
}

type Post {
  primaryId: ID!
  secondaryId: ID!
}
```

And it was parsed into the following Document:
```
    {
      kind: 'Document',
      definitions: [
        {
          kind: 'SchemaDefinition',
          description: undefined,
          directives: [],
          operationTypes: [Array],
          loc: [Object]
        },
        {
          kind: 'ObjectTypeDefinition',
          description: undefined,
          name: [Object],
          interfaces: [],
          directives: [],
          fields: [Array],
          loc: [Object]
        },
        {
          kind: 'ObjectTypeDefinition',
          description: undefined,
          name: [Object],
          interfaces: [],
          directives: [],
          fields: [Array],
          loc: [Object]
        },
        {
          kind: 'ObjectTypeDefinition',
          description: undefined,
          name: [Object],
          interfaces: [],
          directives: [],
          fields: [Array],
          loc: [Object]
        }
      ],
      loc: { start: 0, end: 202 }
    }
```

**Comment by iamdavidmartin** [comment]
So sorry for the delay in this @fwang.

TD;DR: There isn't a satisfying solution to this request, I recommend closing it.

The invalid schema does indeed contain an error - it's missing an input type called `PostInput`. But, as we know, that error is not found by the `graphql/language` library. That library does find other errors, but they're limited to syntax errors. That can be useful, but it can also be confusing to users who would expect all errors to be caught with error checking. It's a tradeoff.

To catch all errors, you have to use a library called `graphql-tools` and its function called `makeExecutableSchema`. That will in fact catch the error in the invalid schema I provided, but it introduces other problems. AWS Amplify has custom directives and data types that are used in AppSync GraphQL schemas and those must be provided to `makeExecutableSchema`, otherwise using normal AppSync directives & data types will cause the parsing of the schema to fail.

That means that only remaining solution is to use the same tools that `aws-amplify` because it will contain those directives & data types. Well, in their source code everything is tightly coupled and you can't validate a schema without starting a local server to listen for connections. I don't think working with this library would result in a maintainable addition to SST.

So that's where it stands. Thank you for being receptive to my request.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
