### ISSUE TITLE
Add `exclude` option for Function to exclude certain directories

### ISSUE THREAD

**Issue by rakcy** [sst/sst#720]
When creating a [Function](https://docs.serverless-stack.com/constructs/Function#configure-bundling-a-python-function), there is no option to exclude directories from the `srcPath`. This `exclude` should be able to interact with CDK's [`AssetOption.exclude`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html#exclude) directly

One usage of this would be for python sources that have their `.venv` in the same directory as the `Pipfile`.

Without the `exclude` of `.venv`, the `.venv` is bundled together with the lambda, including the packages installed by the dependency builder on the docker, effectively copying the packages twice. This bloats the python runtime lambda code and can lead to failed deployments due to exceeding the [250MB Deployment package size](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)

**Comment by sladg** [comment]
Exclusion is needed in case of using Poetry. Bundling will try to include `.sst` folder in bundle, causing error. This happens when having `poetry.lock` in root folder together with `sst.config.ts`.

Offending line here: https://github.com/sst/sst/blob/eebcb438bdac4b17e2ecdf2ffa87666484b1a2dd/packages/sst/src/runtime/handlers/pythonBundling.ts#L137C1-L139C6

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
