### ISSUE TITLE
CLI: Watcher not detecting changes

### ISSUE THREAD

**Issue by jayair** [sst/sst#727]
Steps to reproduce:

- I added a new stack `lib/ApiStack.js` to the `lib/index.js`.
- The watcher picked those changes up and prompted me to deploy it. I did.
- Then I tried making some other changes to the `lib/ApiStack.js`. But it didn't detect them.

**Comment by preshetin** [comment]
This happens because new files don't get added to `inputFiles` array of the `CdkWatcherState` object. 

After some digging I found that while `.build/lib/.esbuild.json` file gets updated at `transpile()` function, it does not get updated during `reTranspile()`. Here's how it gets handled during transpile: https://github.com/serverless-stack/serverless-stack/blob/40526bab2db669ac2065c81fabd24696cce4674c/packages/cli/scripts/util/cdkHelpers.js#L290

I was able to fix this by adding similar code to the `reTranspile` function. 

How does this feel to you @fwang ? I saw you initially created that `reTranspile` function so it would be good to have your green light on that

**Comment by fwang** [comment]
Hey @preshetin, thanks for looking into this! Yeah, we should update the watcher with the new input files after`reTranspile`. I think we do something similar for Lambda functions.

**Comment by preshetin** [comment]
Thanks @fwang for your input. This also can be fixed without writing to a file. This may be a better idea since writing to a file can affect performance. 

If the job of `reTranspile` function is to produce a list of input files then it's doing it wrong. I believe there is a bug here: https://github.com/serverless-stack/serverless-stack/blob/40526bab2db669ac2065c81fabd24696cce4674c/packages/cli/scripts/util/cdkHelpers.js#L300-L304 Currently, Esbuild builds an object that contains a list of files. But it puts it in memory, and since it does not get assigned to a variable this data gets lost. 

So the fix can look like this:
```
 async function reTranspile() {
-  await esbuild.build(esbuildOptions);
-  const metafile = path.join(buildDir, ".esbuild.json");
-  return await getInputFilesFromEsbuildMetafile(metafile);
+  const result = await esbuild.build(esbuildOptions);
+  return Object.keys(result.metafile.inputs).map((input) => path.resolve(input));
 }
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
