### ISSUE TITLE
Support building node lambda in Docker

### ISSUE THREAD

**Issue by NickBlow** [sst/sst#792]
When bundling, there are some libraries that need to be compiled to the Lambda runtime architecture, specifically binaries - it would be great if you could expose the forceDockerBundling flag of https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html#nodejs-function as well. 

Thanks a lot for the great lib.

**Comment by thdxr** [comment]
Hey @NickBlow 

Can you tell us more about what you mean by including binaries? I've been achieving this with the `bundle.copyFiles` option to copy over any additional things I need in the lambda environment and can omit them from being bundled with `bundle.external` 

Additionally we also have the `bundle.nodeModules` prop which will install packages instead of bundling them via esbuild.

**Comment by NickBlow** [comment]
Hi @thdxr, thanks for the reply.

My issue is I have a binary that is installed via npm. As I am on MacOSX M1, the binary is compiled for a different target architecture than AWS Lambda, so I can't copy from node_modules naiively. Usually I solve this by building the lambda in docker if there is anything that needs to be compiled.

I worked around this by including a Lambda Layer which built the binary in docker, but it felt like an unnecessary extra step.

**Comment by thdxr** [comment]
Adding a lambda layer is actually the preferred way to do this because it reduces having to do this step once per function.  Can skip the layer part during local dev.

Is this for Prisma by chance? I had a similar issue but Prisma supports installing other architecture binaries throough specifying an environment variable.

We are working on a new runtime implementaton which should enable us to easily add the ability to  build inside docker but that's probably a month out at least.

**Comment by harrycollin** [comment]
I've also encountered a situation where this would be useful. In my case I'm using node canvas which needs compiling.

**Comment by jayair** [comment]
@harrycollin can you share a doc on how you use this package in Lambda?

**Comment by harrycollin** [comment]
I don't have anything working right now, but my use case closely follows what's discussed here. https://discourse.threejs.org/t/nodejs-threejs-gltfexporter-server-side-blob-issue/4040

**Comment by jayair** [comment]
Usually for layers that people use with Node, they build the Layer separately and just reference the ARN everywhere.

**Comment by chayakumart** [comment]
It looks like the --path option is not working as expected in SST v2 when
starting the frontend application. Instead, you can specify the working
directory for the react-scripts start command by using the --cwd option.

Try the following command instead:

sst env --cwd=../app \"react-scripts start\"d=../app \"react-scripts start\"

This should set the working directory for the react-scripts start command
to the app directory, which is one level above the SST directory.

**Comment by harrycollin** [comment]
> Usually for layers that people use with Node, they build the Layer separately and just reference the ARN everywhere.

This was the solution in my case. But I still think this feature of being able to have your function built within a container would be useful for some cases.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
