### ISSUE TITLE
API: Generate OpenAPI spec

### ISSUE THREAD

**Issue by thdxr** [sst/sst#810]
This can be done in the synth callback in App and processing all the routes in API to generate an OpenAPI spec.  Can start with something basic and build on top of it

#### Requests
- https://github.com/serverless-stack/serverless-stack/discussions/808

**Comment by jpmtrabbold** [comment]
@thdxr  Wow that's awesome! If you want a good reference on what can be achieved, please check this out: https://github.com/lukeautry/tsoa

Not only it generates the spec, but validates the payload to verify if it is according to the spec/typescript models.

**Comment by thdxr** [comment]
I'm actually building something like this for myself for use with JSON:API https://github.com/ironbay/anchor

I think we might start out simple with this but we'll see

**Comment by jpmtrabbold** [comment]
@thdxr that's cool! Maybe have a quick look at the [docs](https://tsoa-community.github.io/docs/) - you might even want to use tsoa internally, as it is flexible to accommodate any framework. Not insisting though - just showing you the option so you don't have to reinvent the wheel :)

**Comment by thdxr** [comment]
Added it to my list to explore further 🙂

**Comment by maciejgoscinski** [comment]
Thanks to the SST slack I found this [PoC](https://github.com/simonireilly/poc-openapi)

This is a good starting point, and there's also a [feature request at TSOA ](https://github.com/lukeautry/tsoa/issues/1105)directly to investigate possible integration with SST.

It seems to me that first-class support for OpenAPI (generating the spec from typescript interfaces AND runtime validations) would be an extremely useful addition to the SST itself at some point in time.

**Comment by maciejgoscinski** [comment]
Since we're actively trying to patch-up a decent solution in our team (but no fully satisfactory result yet) I'm going to at least share the full set of goals we're trying to solve. Almost entirely all of our backend source code is written in Typescript, so the goals are very biased towards that.

### Generating a rich OpenApi spec (roughly achieved with Mr Simon's [PoC](https://github.com/simonireilly/poc-openapi))
- endpoint routes extracted from SST (or the other way around, SST extracting them from e.g. the Controller annotations in TSOA), extended with server baseUrl information (deployed URLs, domains from hosted zones). This is solved by deep-merging the OpenApi generated from sources, with OpenApi generated from deployed ApiGw.
- model specifications generated from Typescript interfaces ("annotated" with jsdoc comment extras, as in TSOA)
- other request specifications (path params, query params, headers) also generated, possibly from an annotation-based class syntax as in TSOA
- sharing the generated spec with the consumers of our API and using it our SwaggerUI or similar solution

### Using the spec to validate in runtime (we're still having troubles)
- full request validation with respect to the provided spec
- parsing the incoming data to fit the spec:
    - auto-casting query / path params to their declared types (e.g. string -> number)
    - possible configuration of "additional properties" treatment to REJECT / SILENTLY_REMOVE / RETAIN
- "runtime" in "runtime validation" refers to one of two possibilities
    - validation and parsing inside the lambda handler itself, preferred because of better control over error messages as well as ability to test handler functions (including the validation) quickly
    - validation only on ApiGateway level, known problems include poor error messages (e.g. "cannot match schema {0} or {1}" when referring to union types, such as Dog | Cat, instead of a more accurate message such as "Dog.name length exceeded, limit 10")

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
