### ISSUE TITLE
NextjsSite: clean up Lambda@Edge function on remove

### ISSUE THREAD

**Issue by fwang** [sst/sst#835]
## Solution 1: Custom Resource
According to [aws doc](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-delete-replicas.html)
> Replicas are typically deleted within a few hours.

So the CR should work if it can use the `AWS::CloudFormation::WaitCondition` and keep retrying for 12hrs.

Pros:
- removal logic is self-contained in the stack

Cons:
- removal can take long (hours) to complete

Things to check:
- [ ] Check if CFN stack has remove timeout
- [ ] Check if CFN custom resource has timeout
- [ ] Check if CFN custom resource has a timeout of 12hrs, can we chain 2 CRs together and retry up to 24hrs, in case we had to wait longer.

## Solution 2: SST singleton stack
Create an SST stack per account to facilitate removing the functions. The edge functions are marked as `retain`, and the SST stack will remove it asynchronously.

Pros:
- removal is quick

Cons:
- added complexity on deploy and remove, need to check for the existance and health of the SST stack
- SST stack might need to be stateful. Removing the SST stack and redeploy can result in dangling edge functions

---
Requests:
- Sam Wrigley https://serverless-stack.slack.com/archives/C01UJ8MDHEH/p1634554715284800
- Roberto https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645683052902419?thread_ts=1641330960.446700&cid=C01JG3B20RY
- Cody https://discordapp.com/channels/@me/1023601158515855410/1024750279117262938

**Comment by iDVB** [comment]
@fwang I do prefer to keep stack self-contained, however, I think I'm leaning more to **Solution 2**.
It's mainly due to that needing to wait 2hrs for each stack to finish deleting.  
For us, this would likely cause a number of issues with our CI pipeline.

Our pipeline builds environments each time a Github branch of type `feat-*` is created and results in a stack of type `projectxyz-branchname`.
Typically we let CFN / CDK auto generate the names of all resources so there are no collisions with other stacks.
That stack is then auto-deleted when the branch is deleted/merged.

There are a number of ways I think Solution 2 could be accomplished. 
1) have functions tagged as Needs deleting or something and have a cron deal with it.
2) sst stack stores list of functions needing deleting (ddb?)
3) some kind of delated queue, where the it tries to delete on some interval until successful.

**Side-thought:**
We get around this Lambda@Edge-delete-time issue now but making sure that we use a separate, singleton stack for all lambda@edge functions and then have all stacks needing access to them to reference the singleton's exported output for the function's ARN / Role. This is ideal and allows for the consuming stacks to be created / deleted quickly. 

Thought about if there was a creative way to solve this for NestJS by changing the routing edge function to get its routing data from the s3 bucket or something so that the statefulness of the routes are **not** stored in the NestJS router and instead somewhere else like the s3 buckets that back them. We do something similar to this with [middy-reroute](https://www.npmjs.com/package/middy-reroute) by storing an [_redirects](https://docs.netlify.com/routing/redirects/) file in the s3 bucket.

**Comment by dkershner6** [comment]
> Create an SST stack per account to facilitate removing the functions.

By this, do you mean something effectively similar to `cdk bootstrap`?

**Comment by fwang** [comment]
@dkershner6 Yup. Exactly that. Curious to hear your thoughts on this approach vs the solution #1?

**Comment by dkershner6** [comment]
> @dkershner6 Yup. Exactly that. Curious to hear your thoughts on this approach vs the solution #1?

I am not totally familiar with how the CDK handles extremely long custom resources, but I do know that I have experienced some having to do with the DynamoDB Global tables. I think they are also dealing with timelines longer than 15 minutes, and therefore need something more resilient in place.

I have not dug deeply, but I could see based on some minimal troubleshooting I did that they were using Step Functions in order to wait longer.  This may be an outdated concept, as it appears you believe you can wait for 12 hours, and I believe I remember something about an extension about 20 versions ago.

All this to say, I have experienced #1 for replication heavy CDK processes already, up to a max of about 4 hours, so I don't feel it would be an antipattern to do so.  I have also setup my CI/CD to handle extremely long, but low usage workloads when dealing with the CDK for this reason.  I would say using GitHub hosted runners as a guide is likely a good plan, as many use it, and they max out at 6 hours.

I'd suggest that if you feel there is a real possibility of exceeding 6 hours, go with the more robust, but more difficult to maintain solution 2.  If 6+ hours would be an extreme outlier, go with solution 1.  Based on AWS's wording, i'd suggest Solution 1, because they tend to sandbag (go really high) on their estimates.

**Comment by electblake** [comment]
I think Solution 1 is reasonable, even though I do loath my stacks being locked up for long periods of time.

This specific case is hardly the only instance of potentially long waits - so whatever is most reliable is always key for me when it comes to IaaC. I'll happily wait for long periods as long as my IaaC is eventually consistent 100% of time.

**Comment by dkershner6** [comment]
I am just wondering how to implement Solution 2 in a way that has the least amount of downsides. This particular problem seemingly has no great solution inside AWS in my experience.

SQS would incur cost if nothing is ever in the Queues, even if it is pretty low cost nowadays.
Eventbridge (CloudWatch Events) has lowish (300) limits on Rules, and continually creating, deleting and calculating crons can be cumbersome.
Step Functions are fairly brutal in terms of price per state change, though they would be free when none are active, and I assume the uses of this functionality would be pretty rare.

I wish they would impose a delay on SNS similar to the visibility one on SQS, that would solve this issue entirely.

**Comment by fwang** [comment]
@dkershner6 thanks for laying out the options!

> SQS would incur cost if nothing is ever in the Queues
You get charged for idle queues?

**Comment by dkershner6** [comment]
> You get charged for idle queues?

You do not, you only get charged for requests (publishing or checking the queue).

In this case, I am referring to the lambda function polling (checking) the queue on a continual basis.  It's cheap, but not zero.  I am unsure what the acceptable cost threshold is, though.

For your knowledge, some back of napkin math:

Default is 20 seconds, which means about 21,600 per day or 648,000 per month (about 25 cents).

You can be crafty and use a CRON lambda instead, and poll yourself, but you lose the ability to scale massively (probably OK here).

Again, not sure any of this is really a concern, just this problem has crossed my desk several times and I haven't seen a perfect solution.

**Comment by iDVB** [comment]
Not sure I'm following the cost or scaling issue. Isn't it good enough to just setup a function that is set to run 2hrs after a stack comes down? In that way it only needs to run once per stack delete, no?

**Comment by dkershner6** [comment]
> just setup a function that is set to run 2hrs after a stack comes down

Expand on this using AWS service names and the word "trigger" in reference to Lambda, please @iDVB .

> In that way it only needs to run once per stack delete, no?

Unless it fails, then you would need to retry.

> Not sure I'm following the cost or scaling issue.

There is no scaling issue, other than we need something that can scale to exact or near zero. Mostly AWS constraints as issues, and a slight mention of cost, also in reference to non-zero.

**Comment by iDVB** [comment]
@dkershner6 
## EventBridge > Step Function Workflow
I've not personally used Step Functions yet, but as I understand it you can have the workflow sit there ready for you to trigger the start via EventBridge CloudFormation Event. Then have the workflow [wait 2hrs](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-wait-state.html) then try to delete replica function, if not back to waiting.

## EventBridge > Lambda > DLQ > Lambda
Again, haven't really taken advantage of DLQs but could you not, have the Lambda try to delete the function and if fail, end up in the DLQ, then using batch window feature (5mins) or a [delay queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html) and then try again. 

## EventBridge > Lambda (Create EventBridge 2hr Cron Rule)
Have CDK 
1. create a "Try Delete Orphan Function" Lambda
2. create a "Create 2hr Cron Function"
3. create an EventBridge Rule on CloudFormation Stack Delete that triggers your function in #2
4. The lambda in #2 then uses the SDK to create an EventBridge Rule that crons every 2hrs and triggers the function in #1
5.  Function in #1 then try deleting the orphan function and fails, or succeeds and uses the SDK to delete the cron in #3

I would think something of one of those would work fine and have very minimal costs, no?

**Comment by iDVB** [comment]
Any updates on anything on the NextJS Edge function issue front?
We'd LOVE use NextJS on a platform we're building right now... but the stack crash on delete is blocking for us.

**Comment by iDVB** [comment]
Would something like this work? @fwang @dkershner6 ...
## Proposed Process

- `sst.EdgeLambda` extends `sst.Function`
    - Creates Helper Resources
        - `CustomResourceA` + `FunctionB`
        - `FunctionC`
- `sst.EdgeLambda` is `retain: true`
- `CustomResourceA` + `FunctionB` that creates an `EventBridgeRule` to CRON `FunctionC` every 1hr when Distro is deleted
- `FunctionC` attempts to delete `sst.EdgeLambda` and if succeeds it first deletes the `EventBridgeRule` and then [deletes itself](https://gist.github.com/jpbarto/38ce994ced3f85128243d50fc11b7b0b)

**Comment by dkershner6** [comment]
@iDVB , I don't see any issue with that pattern, so long as the self delete actually works and is reliable.

I think that `FunctionB` can just be the custom resource itself, but perhaps that is what you meant. I don't see a reason to combine functions.

I think `FunctionC` can just extend `sst.Cron`, and be set to an expression that equates to never, then change to hourly on delete.

I like the self contained nature of this, I worry a little about excessive event bridge rule use, perhaps there is a way to share if an account has more than one Next.js Site, but that's a minor concern, and something has to give in long term retries.

**Comment by iDVB** [comment]
@dkershner6 

>self delete actually works and is reliable

My thoughts as well... never considered this would be possible, so it will be one of the first things I'm going to try.

> I think that `FunctionB` can just be the custom resource itself, but perhaps that is what you meant. 

💯 👍 


> I think `FunctionC` can just extend `sst.Cron`, and be set to an expression that equates to never, then change to hourly on delete.

Oooooh, def going to look into that. Thanks!

> perhaps there is a way to share

Yes, I'm not concerned but I did wonder if there is a way to just have all the edge functions share the same custom resource (distro depends on cr) 

Anyway, I'm about 70% into stubbing this all out. I'll report back with findings.

**Comment by dkershner6** [comment]
> Yes, I'm not concerned but I did wonder if there is a way to just have all the edge functions share the same custom resource (distro depends on cr)

I generally only get concerned about things with low limits (event bridge rules at 300, soft limit, for example). I recommend creating custom resources with reckless abandon.

**Comment by iDVB** [comment]
@dkershner6 didn't realized there was a soft limit. Likely, it is only a soft limit though. 
We've already hit our Distro, EdgeFunction and S3 Bucket soft-limits and had them raised same-day with a single AWS ticket. 

As an upside, we're limited to 4x edge-functions per distro anyway ... so at worst, its only `N * 4`. `N` being the distros. 
But all good considerations. Especially when building something that could potentially be used in many other constructs, not just NextJS.

**Comment by iDVB** [comment]
## Lambda@Edge Deletes Fixed?: 
I think I have a working/tested solution/construct for ensuring that stacks with edge functions in them, can get deleted successfully, while ensuring the edge function also get deleted after the 2hr replication delay.

- [We talk about it here](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1643138747175800)
- [Here is the branch with a working construct ](https://github.com/iDVB/serverless-stack/blob/ec3b66edfba055e493355e746dc80b85b4124363/packages/resources/src/EdgeFunction.ts#L19)(`sst.EdgeFunction`)

So far, the test is only with deleting the original function (no Distro or replicas) and with a 1min delay… but it does prove the case that this is possible and would very likely work with EdgeFunctions as well, since they just need to wait the extra 2hrs.

## Next steps:
- polish cleanup lambda to catch can’t delete lambda error and complete gracefully
- consider putting a boolean `isEdgeFunction` or similar on `sst.Function` or doing this as its current `sst.EdgeFunction` which simply extends `sst.Function`
- celebrate? :tada:

## Approval Needed
@fwang should I continue with this? Did you want to talk how it might be integrated? I was debating on which would be better to set it up ….like this….
`sst.Function > sst.EdgeFunction > cdk.EdgeFunction`
or like this…
`sst.EdgeFunction > cdk.EdgeFunction`
(duplicating most of the internals of `sst.Function` but getting the helpers and prop omits/restrictions of `cdk.EdgeFunction`)

Also, another consideration….
right now I’m wondering if its still a bit brittle since you have to make the primary resource in the template “retain”.
I think there is an edge case here though.  …. what SHOULD happen when the EdgeFunction (retain) is created but then something fails when CFN gets to adding it to the Distro. (ex. func mem too high) the stack will fail and rollback, deleting all resources and “retaining” the EdgeFunction.

I wonder if this whole process would be better to have a CR manage any “retain” resources instead… their-by keeping the stack clean without any retains?

This is what that edge case (mem to high) above (no pun intended) looks like once rolled back.
![image](https://user-images.githubusercontent.com/189506/152178571-876bffe9-bd46-49eb-93c6-c3dbde2dbed8.png)

**Comment by fwang** [comment]
Yeah let's go with `sst.EdgeFunction` for now. We can decide to merge it into `sst.Function` later.

I guess there is the corner case that `functionC` fails to delete itself, and will be orphaned. But I guess there's no way around that? 🤔

**Comment by danieloi** [comment]
@iDVB great job!
I'm trying out your code at the point you shared it and was wondering if there's anything gotcha I should know about.
Also not sure what you go by on the discord but I'd like to maybe chat on this if you have the time

**Comment by fwang** [comment]
Quick update on this. We recently added this concept of an `SSTBootstrap` stack. The `SSTBootstrap` stack isn't a part of ur SST app. It is deployed once per AWS account/region.

We can deploy a Step Function in the SSTBootstrap stack that helps with removing an Edge function, and retries if fails.

NextJsSite's edge functions will be marked as RETAIN, and let the Step Function remove it.

It's similar to the Cron job idea above. The difference being we can use Step Functions instead, and move the resources out of user's app to the SSTBootstrap stack.

**Comment by iDVB** [comment]
@fwang Oh wow... is this all fully baked and usable now with NextJsSite? 🚀

**Comment by cbravo** [comment]
Just wondering what the status of this is? Is it still on the radar?

**Comment by jayair** [comment]
Most likely we'll fix this in Ion instead of patching CFN https://github.com/sst/ion

**Comment by jayair** [comment]
Yeah Remix is on the roadmap for v1.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by why-el** [comment]
What was the fix?

**Comment by jayair** [comment]
This thread was for v2. If you are having issues with v3, open a new issue?

**Comment by why-el** [comment]
My bad yeah. I was wondering what the fix is since it was mentioned that this will be fixed in Ion (and this issue is now technically in the same repo). Documenting the fix will help for folks coming in from Google and elsewhere. 

In case it helps the next person, this is what worked for me, and I think it is the pulumi-recommended solution, albeit hacky: 

```
    {
      customTimeouts: {
        delete: "1h",
      },
    },
```

on the edge function definition.
