### ISSUE TITLE
SST needs to track previously deployed stacks, and remove the ones that are not in the subsequent deployment.

### ISSUE THREAD

**Issue by fwang** [sst/sst#880]
Jereme Monteau mentioned that:
> I had split the app into 2 stacks at one point. Those stacks got deployed into CloudFormation. Then I recombined them back into a single stack and when that got deployed, the previous 2 stacks remained and the cron jobs were still running.

**Comment by dkershner6** [comment]
Just commenting that this is typical and expected behavior in Cloudformation and the CDK, and you must explicitly remove stacks rather than just omitting them.

I also believe that this (what I said above) is the right direction to take, as there may be instances where you only want to deploy some of the stacks without removing the others, and see no need for the sst.App to be globally aware of all stacks (unless you use `.addDependency`).

**Comment by Sankha-barui** [comment]
Good

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
